#!/usr/bin/env bash

# Build new directories by cloning exisitng templates
set -x

#getconf [-v specification] variable_name [pathname]
#getconf -a [pathname]

getconf -a ./Templates/default

target=${1:-$(uuidgen)}

find "$target" -type d

cp -r Templates/default  "./${target}"

# echo "Finding directories... "
# find . -type d
#
# echo "Finding files... "
# find . -type f
#
# echo "Finding directories... max depth: 1"
# find . -maxdepth 1 -type d 
