#      AutoDoc Makefile.
# AutoDoc 1.0  Makefile.top
# Copyright (c) Kieran O'Neill, 2025.
# Autodoc may be freely redistributed.  See license for details.



clean:
	ls
	@echo cleaning

spotless: clean
	ls
	@echo cleaning + spotless

#	-rm -f a.out core $(GAME) Sys*
#	-rm -f ../include/date.h ../include/onames.h ../include/pm.h
#	-rm -f ../include/vis_tab.h vis_tab.c tile.c *.moc
#	-rm -f ../win/gnome/gn_rip.h
